## [作業重點]
了解如何使用 Sklearn 中的 hyper-parameter search 找出最佳的超參數

### 作業
請使用不同的資料集，並使用 hyper-parameter search 的方式，看能不能找出最佳的超參數組合

In [1]:
from sklearn import datasets, metrics
from sklearn.model_selection import train_test_split, KFold, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


### 載入wine datasets

In [2]:
digits = datasets.load_digits()
x = digits.data
y = digits.target
print('x:\n', x, '\ny:\n', y, '\nshape of x:\n', x.shape, '\nshape of y:\n', y.shape)

x:
 [[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]] 
y:
 [0 1 2 ... 8 9 8] 
shape of x:
 (1797, 64) 
shape of y:
 (1797,)


#### 資料前處理

In [3]:
# split data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

# MinMaxScaler
mm = MinMaxScaler()
mm.fit(x_train)
x_train = mm.transform(x_train)
x_test = mm.transform(x_test)

#### Random Forest

In [4]:
# default
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
y_pred = rf.predict(x_test)
print('Accuracy: %.4f' % metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9556


#### GridSearch

In [5]:
n_estimators = [400, 500, 600]
max_depth = [5, 6, 7]
max_features  = [6, 7, 8]
param_grid = dict(n_estimators=n_estimators, max_depth=max_depth, max_features=max_features)
grid_search = GridSearchCV(rf, param_grid, scoring="accuracy", n_jobs=-1, verbose=1)
grid_result = grid_search.fit(x_train, y_train)

Fitting 3 folds for each of 27 candidates, totalling 81 fits


[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   19.5s
[Parallel(n_jobs=-1)]: Done  81 out of  81 | elapsed:   36.6s finished


In [6]:
print("Best Accuracy: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Best Accuracy: 0.959911 using {'max_depth': 7, 'max_features': 8, 'n_estimators': 500}


In [7]:
grid_result.best_params_

{'max_depth': 7, 'max_features': 8, 'n_estimators': 500}

#### Use best parameters

In [8]:
rf_bestparam = RandomForestClassifier(n_estimators=500, max_depth=7, max_features=8)
rf_bestparam.fit(x_train, y_train)
y_pred = rf_bestparam.predict(x_test)
print('Accuracy: %.4f' % metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9711
